### ISSUE TITLE
[Design][Spec] Helper Content

### ISSUE THREAD

**Issue by JonathanMontane** [luckymarmot/console-rest#10]
### List
- [ ] Why console.rest ?
- [x] Importing from Paw
- [x] Importing from Postman
- [x] What is Swagger / OAI ?
- [x] What is RAML ?
- [ ] I like to use curl
### Why console.rest ?

A short statement of the mission of console.rest (+ link to blog article ?)
### Importing from Paw

A short statement explaining that import from paw can be done in one click

**Current Iteration**

![image](https://cloud.githubusercontent.com/assets/5136989/18909314/65eef82c-8573-11e6-9f25-cf87bbb77197.png)
### Importing from Postman

2 Tabs:
- Most Data (default)
- Simplest

Each tab contains a list of steps top import the data into console.rest

**Current Iteration**

![image](https://cloud.githubusercontent.com/assets/5136989/18909161/d6d541a0-8572-11e6-931e-8d7699c7e3c2.png)
### Swagger / OAI / RAML
- short description text
- links to specs

**Current iteration**

![image](https://cloud.githubusercontent.com/assets/5136989/18910067/a827e1c4-8576-11e6-911b-bdf12499f17e.png)
### I like to use curl
- Limitations of the curl parser ? (ie, no bash, only curl -> no environment variables, etc)
### Your favourite format is missing ?
- short description
- button with link to issue #12 in Github

**Comment by JonathanMontane** [comment]
@mittsh can you provide me with some feedback on what to change?

**Comment by JonathanMontane** [comment]
> I like to use curl
 
Maybe talk about the possibility console.rest gives to create documentation from a list of curl requests?

**Comment by mittsh** [comment]
@JonathanMontane Looks nice overall 👍 

> Why console.rest ?

Ok I'll think about it. Clearly when we release it we should have a blog article ready so we can paste it here. I think here we should express our desire to keep integrations open source and open to other platforms. Without naming it, we should say why the Run in Postman button was a bad idea. Something like:

*HTTP is great because it's resilient to changes and it's cross platform, and so should be the APIs built on it. We wanted to build an open tool so every API can be easily setup in any testing tool and converted to any description format.*

> Importing from Paw

Love the idea of "one-click import". It's great to say that it's already bundled, instead of making it look like an extra step. (I was trying to find better sentences, but I think yours are good)

I'd center the fox behind the text above the button, so it doesn't get hidden by the button itself.

I like the emerald color of the button! Have you tried to use #00aaff here?

> Postman

Good! The emerald color line underneath "Most Data" seems a little off positioned. It's kind of half way between underline and a box around… maybe 2px lower?

The wrench is too big, but it's good to show it.

Download? Why in orange? Coz of Postman?

> Swagger + RAML

I think we should just have a short sentence like:

*Swagger/RAML is a JSON or RAML based format used to describe RESTful APIs. It describes the available API endpoints, possible responses, security schemes and more.*

Put their logo in B&W and a link to their GitHub page or homepage, whichever is nicer (the Swagger homepage is awful so I'd go for the GitHub, but RAML is quite nice).

> cURL

I don't have so much opinion about cURL here… Start with a sentence saying that curl is great and often helpful (CLI fanboys will like it), and then express the limitations.


Lastly, how about a block about other missing formats? *Looking for another format or tool?* And encourage people to file an issue on GitHub to request another platform. It will be interesting to see what people want next. API Blueprint? HTTPie? etc.

**Comment by JonathanMontane** [comment]
> HTTP is great because it's resilient to changes and it's cross platform, and so should be the APIs built on it. We wanted to build an open tool so every API can be easily setup in any testing tool and converted to any description format.

Nice but I think it's possibly too long already. I'll come back to you with synthesized version.

> I like the emerald color of the button! Have you tried to use #00aaff here?

Yes, and it doesn't look good 😞  (which is why I went with the light sea green)

> Good! The emerald color line underneath "Most Data" seems a little off positioned. It's kind of half way between underline and a box around… maybe 2px lower?

> The wrench is too big, but it's good to show it.

It was a very rough sketch to get the general idea ✏️ 

> Download? Why in orange? Coz of Postman?

This was to give a visual reminder of what the download button looked like in Postman, but I'm not sure it matches our color scheme anyway. I'll see how it goes and update accordingly.

> Swagger/RAML is a JSON or ~~R~~**Y**AML based format used to describe RESTful APIs. It describes the available API endpoints, possible responses, security schemes and more.

👍 

> Lastly, how about a block about other missing formats? Looking for another format or tool? And encourage people to file an issue on GitHub to request another platform. It will be interesting to see what people want next. API Blueprint? HTTPie? etc.

👍

**Comment by JonathanMontane** [comment]
> Lastly, how about a block about other missing formats? Looking for another format or tool? And encourage people to file an issue on GitHub to request another platform. It will be interesting to see what people want next. API Blueprint? HTTPie? etc.

@mittsh created https://github.com/luckymarmot/console-rest/issues/12

**Comment by JonathanMontane** [comment]
### Import from Postman

#### Current iteration
![image](https://cloud.githubusercontent.com/assets/5136989/18909161/d6d541a0-8572-11e6-931e-8d7699c7e3c2.png)

#### Past iterations

![image](https://cloud.githubusercontent.com/assets/5136989/18906054/3e1a593e-8566-11e6-8ef0-48f48467be85.png)

**Comment by JonathanMontane** [comment]
### Import from Paw

#### Current iteration
![image](https://cloud.githubusercontent.com/assets/5136989/18909314/65eef82c-8573-11e6-9f25-cf87bbb77197.png)

#### Past iterations
![image](https://cloud.githubusercontent.com/assets/5136989/18905965/d5cb2de0-8565-11e6-889c-db6ed9381214.png)

**Comment by JonathanMontane** [comment]
### Swagger, OAI, RAML

#### Current iteration
![image](https://cloud.githubusercontent.com/assets/5136989/18910067/a827e1c4-8576-11e6-911b-bdf12499f17e.png)

#### Past iterations

**Comment by mittsh** [comment]
> Postman

👍 

> Paw, Swagger, RAML

👍  But increase the line height, it's too packed. Possibly make the text smaller to differentiate with the title (applies to Postman too).
